### ISSUE TITLE
xsm does not start on Ubuntu MATE 20.04 LTS

### ISSUE THREAD

**Issue by N0rbert** [nlpsuge/xsession-manager#22]
Steps to reproduce:

1. Have Ubuntu MATE 20.04 LTS installed
1. Install `xsession-manager` as follows:

       sudo apt-get install python3-dev wmctrl python3-pip python3-tk curl libcurl4-openssl-dev libssl-dev python-is-python3
       sudo pip3 install xsession-manager

1. Try to launch it by `xsm`

Expected results:

* `xsm` shows usage

Actual results:

* `xsm` shows error as follows:

      $ xsm
      Traceback (most recent call last):
        File "/usr/local/bin/xsm", line 8, in <module>
          sys.exit(run())
        File "/usr/local/lib/python3.8/dist-packages/xsession_manager/main.py", line 10, in run
          check_login_condition()
        File "/usr/local/lib/python3.8/dist-packages/xsession_manager/main.py", line 27, in check_login_condition
          original_login_user = os.getlogin()
      OSError: [Errno 6] No such device or address

I'm not a Python expert, but simple searching gives the idea to change `os.getlogin()` → `os.getenv('LOGNAME')`. This fixes this bug.

**Comment by nlpsuge** [comment]
I'll look into this issue later.

**Comment by nlpsuge** [comment]
Hi,
Thanks for reporting this issue very much.

I believe that changing os.getlogin() to os.getenv('LOGNAME') cannot fix this bug.

I use os.getlogin()  in order to **get the actual user** who has logged in a terminal in the first place.

Let's do some tests on Ubuntu MATE 20.04 LTS:

```Bash
# Add a user named test
ubuntu-mate@ubuntu-mate:~$ sudo adduser test
adduser: The user `test' already exists.

# Switch to test by using su
ubuntu-mate@ubuntu-mate:~$ su test
Password: 

# Go into the python terminal
test@ubuntu-mate:/home/ubuntu-mate$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import getpass
>>> os.getlogin()
'ubuntu-mate'  # This is the expected username
>>> os.getenv('LOGNAME')
'test'  # This is the wrong username, it should be  ubuntu-mate
>>> getpass.getuser()
'test' # This is the wrong username, it should be  ubuntu-mate
>>> 

```
So if you change os.getlogin() to os.getenv('LOGNAME'), you may save the _**ubuntu-mate**_' xsession as _**test**_ and restore _**ubuntu-mate**_' xsession after logging in _**test**_ account.

```os.getlogin()``` works like a charm on Ubuntu MATE 20.04 LTS in my case. I don't know why you run into this issue.

Can you execute this cmd in the terminal and attach the file named output.txt, it may help me to address the problem:
```strace -o output.txt python -c 'import os;print(os.getlogin())'```

I'm finding an alternative to ```os.getlogin()```

**Comment by N0rbert** [comment]
For `strace -o output.txt python -c 'import os;print(os.getlogin())'` I have the following:

```
mate@focal:~$ strace -o output.txt python -c 'import os;print(os.getlogin())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 6] No such device or address
mate@focal:~$ 
```
[output.txt](https://github.com/nlpsuge/xsession-manager/files/6132753/output.txt)

This Ubuntu MATE 20.04.2 LTS system is installed into VirtualBox.

---

I have the same behavior when I install and launch xsm inside of live session of http://cdimage.ubuntu.com/ubuntu-mate/releases/20.04.2.0/release/ubuntu-mate-20.04.2.0-desktop-amd64.iso .

**Comment by nlpsuge** [comment]
Hi,

What do you get if execute  **`logname`** in a ternimal befere and after executing `su please_replace_with_your_username`?

What do you get if execute  **`whoami`** in a ternimal befere and after executing `su please_replace_with_your_username`?

**Comment by N0rbert** [comment]
Below is what I have:

```
mate@focal:~$ whoami
mate
mate@focal:~$ logname 
logname: no login name
mate@focal:~$ su mate
Password: 
mate@focal:~$ whoami 
mate
mate@focal:~$ logname 
logname: no login name
mate@focal:~$ 

```

**Comment by nlpsuge** [comment]
> I have the same behavior when I install and launch xsm inside of live session of http://cdimage.ubuntu.com/ubuntu-mate/releases/20.04.2.0/release/ubuntu-mate-20.04.2.0-desktop-amd64.iso .

I downloaded http://cdimage.ubuntu.com/ubuntu-mate/releases/20.04.2.0/release/ubuntu-mate-20.04.2.0-desktop-amd64.iso and run it in VirtualBox. I can launch xsm without issues. 

I think some config files in your OS is corrupted, but I'm not sure.

**Comment by nlpsuge** [comment]
> Below is what I have:
> 
> ```
> mate@focal:~$ whoami
> mate
> mate@focal:~$ logname 
> logname: no login name
> mate@focal:~$ su mate
> Password: 
> mate@focal:~$ whoami 
> mate
> mate@focal:~$ logname 
> logname: no login name
> mate@focal:~$ 
> ```

Which terminal did you use to execute those commands?

Can you use other terminals, like guake, gnome-terminal and try again? If you still have 'logname: no login name', I suggest you create a new account and execute `logname` in this new account.

**Comment by N0rbert** [comment]
Very interesting.

It is default MATE Terminal, with default locale. 
My daily Ubuntu MATE 18.04 LTS also fails with `logname` command. But I'm sure that it is configured correctly.
On all systems I see that `logname` work normally only in `<Ctrl>+<Alt>+<F1>` text terminal.
So for me it is very strange that you can not reproduce this.

**Comment by nlpsuge** [comment]
> 
> [output.txt](https://github.com/nlpsuge/xsession-manager/files/6132753/output.txt)

These two lines in output.txt indicate some problem:
```
openat(AT_FDCWD, "/proc/self/loginuid", O_RDONLY) = 3
read(3, "4294967295", 12)               = 10
```

Please run `cat /proc/self/loginuid` in the Mate Terminal and the text terminal and tell me the result.

I think the result in the Mate Terminal is 4294967295 and another equals `id -u`.

4294967295 means `/proc/self/loginuid` is unset, but if using Mate Terminal to run `cat /proc/self/loginuid` the result should be like 1001 etc normally.

See also:
1. https://unix.stackexchange.com/questions/347889/a-proper-replacement-for-the-logname-utility/348218#348218
2. http://www.linux-pam.org/Linux-PAM-html/sag-pam_loginuid.html
3. https://linux-audit.redhat.narkive.com/mTXdCUES/why-auid-always-unset
4. https://unix.stackexchange.com/questions/146138/loginuid-should-be-allowed-to-change-or-not-mutable-or-not

**Comment by nlpsuge** [comment]
Can you use other terminals (not Mate terminal, gnome-terminal) to run `cat /proc/self/loginuid` or `logname`?

**Comment by N0rbert** [comment]
I did tests with `cat /proc/self/loginuid; logname; id -u; xsm`. Below is what I have:

| **Terminal** | **`cat /proc/self/loginuid`** | **`logname`** | **`id -u`** | **`xsm`**|
|--------------|-------------------------------|---------------|-------------|----------|
| `mate-terminal` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `gnome-terminal` | 1000 | mate | 1000 | ok | 
| `konsole` | 1000 | mate| 1000 | ok |
| `cool-retro-term` | 1000 | mate| 1000 | ok |
| `deepin-terminal` | 4294967295 | `logname: no login name` | `1000` | fail | 
| terminal in Geany | 1000 | mate | 1000 | ok |
| `guake` | 1000 | mate | 1000 | ok |
| terminal in Kate | 4294967295 | `logname: no login name` | `1000` | fail | 
| `kitty` | 1000 | mate | 1000 | ok |
| `lilyterm` | 1000 | mate | 1000 | ok |
| `lxterminal` | 1000 | mate | 1000 | ok |
| `mlterm` | 1000 | mate | 1000 | ok |
| `pangoterm` | 1000 | mate | 1000 | ok |
| `pterm` | 1000 | mate | 1000 | ok |
| `qterminal` | 1000 | mate | 1000 | ok |
| `rxvt` | 1000 | mate | 1000 | ok |
| `sakura` | 1000 | mate | 1000 | ok |
| `Terminal` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `terminator` | 1000 | mate | 1000 | ok |
| `terminalogy` | 1000 | mate | 1000 | ok |
| `termit` | 1000 | mate | 1000 | ok |
| `tilda` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `tilix` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `xfce4-terminal` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `xiterm+thai` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `xterm` | 4294967295 | `logname: no login name` | `1000` | fail | 
| `yakuake` | 4294967295 | `logname: no login name` | `1000` | fail | 

There is no bug in `xsession-manager`, the bug is in some library.
